# Generated by Django 3.1.14 on 2023-05-02 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='入会日'),
        ),
    ]
